Add support for parsing (clickable) links (fixes #107) Add support for replacing words from the game to Discord (mc-to-discord-replacer) (fixes #214) Add support for using channel IDs with the /mbroadcast command (fixes #205) Add support for customizing the player list message format Add support for relaying /broadcast commands (from Nucleus) (fixes #194) Fix error when sending empty mentions (fixes #211) Fix HelpOp messages (fixes #217, #199) Fix dependency relocation not working, causing NoSuchMethodErrors (fixes #207) Fix MagiBridge not ignoring it's own messages when using ignore-bots=false (fixes #206 and #189)